---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tutorial-template
spec:
  params:
    - name: repository
      description: git repo
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: tutorial-pipeline
        params:
          - name: repository
            value: "https://github.com/sanjana-soni16/selenium-scripts.git"
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: tutorial-binding
spec:
  params:
    - name: repository
      type: string
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tutorial-listener
spec:
  triggers:
    - binding:
        name: tutorial-binding
      template:
        name: tutorial-template
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  params:
    - name: repository
      description: the git repo 
  workspaces:
    - name: pipeline-ws
  tasks:   
    - name: git-clone
      taskRef:
        name: git-clone-repo
      params:
        - name: ibmcloud-apikey-secret-key
          value: toolchain-apikey
        - name: repository
          value: $(params.repository)
        - name: branch
          value: selenium-test
        - name: directory-name          
          value: "tutorial"
      workspaces:
        - name: output
          workspace: pipeline-ws      
    - name: tutorial-task
      runafter: [git-clone]
      workspaces:
        - name: output
          workspace: pipeline-ws
      taskRef:
        name: tutorial-task
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tutorial-task
spec:
  workspaces:
  - name: output
    mountPath: /artifacts
  steps:
    - name: tutorial
      image: ibmcom/pipeline-base-image
      command: ["/bin/bash", "-c"]
      args:
        - |
          cd /artifacts
          apt-get -y update;
          apt install software-properties-common -y
          add-apt-repository ppa:deadsnakes/ppa -y
          apt-get -y install python3.9;
          echo "apt-get -y install python3-pip;"
          apt-get -y install python3-pip;
          apt-get -y install python3.9-venv
          ls
          python3.9 -m venv venv
          . venv/bin/activate
          python3 -V
          ls tutorial/
          cd tutorial
          pip3 install -r requirements.txt
          ls
          env
          python3 tutorial1.py